<?php

namespace AppBundle\Repository;

/**
 * NotasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotasRepository extends \Doctrine\ORM\EntityRepository
{
}
